import type { INodeProperties } from 'n8n-workflow';

export const ttsOperations: INodeProperties[] = [
    {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: {
            show: {
                resource: ['tts'],
            },
        },
        options: [
            {
                name: 'Get Voices',
                value: 'getVoices',
                description: 'Retrieve available voice models',
                action: 'Get voices',
            },
            {
                name: 'Synthesize Speech',
                value: 'synthesize',
                description: 'Convert text to speech',
                action: 'Synthesize speech',
            },
        ],
        default: 'synthesize',
    },
];

export const ttsFields: INodeProperties[] = [
    // Model for Synthesize
    {
        displayName: 'Model',
        name: 'model',
        type: 'options',
        required: true,
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['synthesize'],
            },
        },
        options: [
            {
                name: 'Lightning V3.1',
                value: 'lightning-v3.1',
                description: 'Fast and high-quality text-to-speech',
            },
        ],
        default: 'lightning-v3.1',
        description: 'The model to use for speech synthesis',
    },
    // Model for Get Voices
    {
        displayName: 'Model',
        name: 'model',
        type: 'options',
        required: true,
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['getVoices'],
            },
        },
        options: [
            {
                name: 'Lightning V3.1',
                value: 'lightning-v3.1',
            },
        ],
        default: 'lightning-v3.1',
        description: 'The model to retrieve available voices for',
    },
    {
        displayName: 'Text',
        name: 'text',
        type: 'string',
        required: true,
        default: '',
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['synthesize'],
            },
        },
        description: 'The text to convert to speech',
    },
    // ---- Voice source selector ----
    {
        displayName: 'Voice Source',
        name: 'voiceSource',
        type: 'options',
        required: true,
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['synthesize'],
            },
        },
        options: [
            {
                name: 'Built-in Voice',
                value: 'builtin',
                description: 'Select from the available Lightning V3.1 voices',
            },
            {
                name: 'Custom Voice ID',
                value: 'custom',
                description: 'Enter a cloned or custom voice ID',
            },
        ],
        default: 'builtin',
        description: 'Choose whether to use a built-in voice or provide a custom voice ID',
    },
    // ---- Built-in voice dropdown (shown when Voice Source = Built-in) ----
    {
        displayName: 'Voice',
        name: 'voiceId',
        type: 'options',
        required: true,
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['synthesize'],
                voiceSource: ['builtin'],
            },
        },
        options: [
            { name: 'Aanya — Hindi · Indian · Female', value: 'aanya' },
            { name: 'Aarush — English, Hindi · Indian · Male', value: 'aarush' },
            { name: 'Advika — English, Hindi · Indian · Female', value: 'advika' },
            { name: 'Aisha — English, Hindi · Indian · Female', value: 'aisha' },
            { name: 'Alex — English · American · Male', value: 'alex' },
            { name: 'Anitha — Tamil · Tamil · Female', value: 'anitha' },
            { name: 'Anuja — English, Hindi · Indian · Female', value: 'anuja' },
            { name: 'Arjun — English, Hindi · Indian · Male', value: 'arjun' },
            { name: 'Atharv — English, Hindi · Indian · Male', value: 'atharv' },
            { name: 'Avery — English · American · Female', value: 'avery' },
            { name: 'Avni — English, Hindi · Indian · Female', value: 'avni' },
            { name: 'Balaji — Tamil · Tamil · Male', value: 'balaji' },
            { name: 'Biance — English · American · Female', value: 'biance' },
            { name: 'Brian — English · American · Male', value: 'brian' },
            { name: 'Brooke — English · American · Female', value: 'brooke' },
            { name: 'Camilla — Spanish · Mexican/Latin · Female', value: 'camilla' },
            { name: 'Carlos — Spanish · Mexican/Latin · Male', value: 'carlos' },
            { name: 'Chinmayi — English, Hindi · Indian · Female', value: 'chinmayi' },
            { name: 'Cooper — English · Australian · Male', value: 'cooper' },
            { name: 'Daniel — English · American · Male', value: 'daniel' },
            { name: 'Daniella — Spanish · Mexican/Latin · Female', value: 'daniella' },
            { name: 'Deepashri — Kannada · Kannada · Female', value: 'deepashri' },
            { name: 'Devansh — Hindi · Indian · Male', value: 'devansh' },
            { name: 'Dhruvit — Gujarati · Gujarati · Male', value: 'dhruvit' },
            { name: 'Diego — Spanish · Mexican/Latin · Male', value: 'diego' },
            { name: 'Dina — English · American · Female', value: 'dina' },
            { name: 'Divya — English, Hindi · Indian · Female', value: 'divya' },
            { name: 'Divyanshu — English · American · Male', value: 'divyanshu' },
            { name: 'Edward — English · British · Male', value: 'edward' },
            { name: 'Elizabeth — English · American · Female', value: 'elizabeth' },
            { name: 'Ella — English · American · Female', value: 'ella' },
            { name: 'Ethan — English · American · Male', value: 'ethan' },
            { name: 'Gabriela — Spanish · Mexican/Latin · Female', value: 'gabriela' },
            { name: 'Gaurav — English, Hindi · Indian · Male', value: 'gaurav' },
            { name: 'Gauri — Marathi · Marathi · Female', value: 'gauri' },
            { name: 'Hannah — English · American · Female', value: 'hannah' },
            { name: 'Harper — English · American · Female', value: 'harper' },
            { name: 'Hitesh — English, Hindi · Indian · Male', value: 'hitesh' },
            { name: 'Ira — English, Hindi · Indian · Female', value: 'ira' },
            { name: 'Ishani — English, Hindi · Indian · Female', value: 'ishani' },
            { name: 'Javier — Spanish · Mexican/Latin · Male', value: 'javier' },
            { name: 'Jeevan — Tamil · Tamil · Male', value: 'jeevan' },
            { name: 'Jessica — English · American · Female', value: 'jessica' },
            { name: 'Johnny — English · American · Male', value: 'johnny' },
            { name: 'Jordan — English · American · Male', value: 'jordan' },
            { name: 'José — Spanish · Mexican/Latin · Male', value: 'jose' },
            { name: 'Kavya — English, Hindi · Indian · Female', value: 'kavya' },
            { name: 'Kevin — English · American · Female', value: 'kevin' },
            { name: 'Kiran — Gujarati · Gujarati · Male', value: 'kiran' },
            { name: 'Kunal — English, Hindi · Indian · Male', value: 'kunal' },
            { name: 'Kyle — English · American · Male', value: 'kyle' },
            { name: 'Lauren — English · American · Female', value: 'lauren' },
            { name: 'Liam — English · British · Male', value: 'liam' },
            { name: 'Lucas — English · American · Male', value: 'lucas' },
            { name: 'Lucia — Spanish · Mexican/Latin · Female', value: 'lucia' },
            { name: 'Luis — Spanish · Mexican/Latin · Male', value: 'luis' },
            { name: 'Magnus — English · American · Male', value: 'magnus' },
            { name: 'Maithili — English, Hindi · Indian · Female', value: 'maithili' },
            { name: 'Mariana — Spanish · Mexican/Latin · Female', value: 'mariana' },
            { name: 'Megan — English, Hindi · American · Female', value: 'megan' },
            { name: 'Mia — English · American · Female', value: 'mia' },
            { name: 'Miguel — Spanish · Mexican/Latin · Male', value: 'miguel' },
            { name: 'Mihir — English, Hindi · Indian · Male', value: 'mihir' },
            { name: 'Mohit — English, Hindi · Indian · Male', value: 'mohit' },
            { name: 'Neel — English, Hindi · Indian · Male', value: 'neel' },
            { name: 'Nicole — English · American · Female', value: 'nicole' },
            { name: 'Niharika — Gujarati, English, Hindi · Gujarati · Female', value: 'niharika' },
            { name: 'Nilesh — Marathi, English, Hindi · Marathi · Male', value: 'nilesh' },
            { name: 'Nirav — Gujarati · Gujarati · Male', value: 'nirav' },
            { name: 'Noah — English · British · Male', value: 'noah' },
            { name: 'Olivia — English · American · Female', value: 'olivia' },
            { name: 'Padmaja — Telugu · Telugu · Female', value: 'padmaja' },
            { name: 'Parth — English, Hindi · Indian · Male', value: 'parth' },
            { name: 'Poppy — English · British · Female', value: 'poppy' },
            { name: 'Prachi — Gujarati · Gujarati · Female', value: 'prachi' },
            { name: 'Pranav — Kannada · Kannada · Male', value: 'pranav' },
            { name: 'Priyanka — Marathi · Marathi · Female', value: 'priyanka' },
            { name: 'Quinn — English · American · Female', value: 'quinn' },
            { name: 'Rachel — English · American · Female', value: 'rachel' },
            { name: 'Rajeshwari — Tamil · Tamil · Female', value: 'rajeshwari' },
            { name: 'Raju — Tamil · Tamil · Male', value: 'raju' },
            { name: 'Robert — English · American · Male', value: 'robert' },
            { name: 'Rupali — Marathi · Marathi · Female', value: 'rupali' },
            { name: 'Sakshi — English, Hindi · Indian · Female', value: 'sakshi' },
            { name: 'Sameera — English, Hindi · Indian · Female', value: 'sameera' },
            { name: 'Sana — English, Hindi · Indian · Female', value: 'sana' },
            { name: 'Sandhya — Tamil · Tamil · Female', value: 'sandhya' },
            { name: 'Sandra — English · American · Female', value: 'sandra' },
            { name: 'Sanket — Marathi · Marathi · Male', value: 'sanket' },
            { name: 'Shibi — Malayalam · Malayalam · Male', value: 'shibi' },
            { name: 'Shrihari — Telugu · Telugu · Male', value: 'shrihari' },
            { name: 'Shyam — English, Hindi · Indian · Male', value: 'shyam' },
            { name: 'Siddharth — English, Hindi · Indian · Male', value: 'siddharth' },
            { name: 'Siya — English, Hindi · Indian · Female', value: 'siya' },
            { name: 'Sophia — English · American · Female', value: 'sophia' },
            { name: 'Srishti — English, Hindi · Indian · Female', value: 'srishti' },
            { name: 'Sunidhi — English, Hindi · Indian · Female', value: 'sunidhi' },
            { name: 'Tara — English · Neutral · Female', value: 'tara' },
            { name: 'Tripti — English, Hindi · Indian · Female', value: 'tripti' },
            { name: 'Vaibhav — English, Hindi · Indian · Male', value: 'vaibhav' },
            { name: 'Vaisakh — Malayalam · Malayalam · Male', value: 'vaisakh' },
            { name: 'Vanessa — English · American · Female', value: 'vanessa' },
            { name: 'Vivaan — English, Hindi · Indian · Male', value: 'vivaan' },
            { name: 'Yuvika — English, Hindi · Indian · Female', value: 'yuvika' },
            { name: 'Zoya — Hindi · Indian · Female', value: 'zoya' },
        ],
        default: 'avery',
        description: 'Select a built-in voice for speech synthesis',
    },
    // ---- Custom voice ID text input (shown when Voice Source = Custom) ----
    {
        displayName: 'Custom Voice ID',
        name: 'customVoiceId',
        type: 'string',
        required: true,
        default: '',
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['synthesize'],
                voiceSource: ['custom'],
            },
        },
        description: 'Enter a custom voice ID (e.g. a cloned voice ID from the Smallest AI dashboard)',
    },
    {
        displayName: 'Output Format',
        name: 'output_format',
        type: 'options',
        required: true,
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['synthesize'],
            },
        },
        options: [
            { name: 'MP3', value: 'mp3' },
            { name: 'Mulaw', value: 'mulaw' },
            { name: 'PCM', value: 'pcm' },
            { name: 'WAV', value: 'wav' },
        ],
        default: 'wav',
        description: 'The format of the output audio',
    },
    {
        displayName: 'Additional Options',
        name: 'additionalOptions',
        type: 'collection',
        placeholder: 'Add Option',
        default: {},
        displayOptions: {
            show: {
                resource: ['tts'],
                operation: ['synthesize'],
            },
        },
        options: [
            {
                displayName: 'Language',
                name: 'language',
                type: 'options',
                options: [
                    { name: 'Auto', value: 'auto' },
                    { name: 'English', value: 'en' },
                    { name: 'Hindi', value: 'hi' },
                    { name: 'Spanish', value: 'es' },
                    { name: 'Tamil', value: 'ta' },
                ],
                default: 'auto',
            },
            {
                displayName: 'Sample Rate',
                name: 'sample_rate',
                type: 'options',
                options: [
                    { name: '8000', value: 8000 },
                    { name: '16000', value: 16000 },
                    { name: '24000', value: 24000 },
                    { name: '44100', value: 44100 },
                ],
                default: 44100,
                description: 'The sample rate for the generated audio',
            },
            {
                displayName: 'Speed',
                name: 'speed',
                type: 'number',
                typeOptions: {
                    minValue: 0.5,
                    maxValue: 2,
                },
                default: 1,
                description: 'The speed of the generated speech',
            },
        ],
    },
];
